[build]
  publish = "."
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false  # Disabled - we handle image optimization manually

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# HTML files - shorter cache for updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

# CSS and JS - moderate cache with revalidation
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

# Optimized images - longer cache but not excessive
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"  # 30 days

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"  # 30 days

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect www to non-www
[[redirects]]
  from = "https://www.personaltrainingbangkokp1.com/*"
  to = "https://personaltrainingbangkokp1.com/:splat"
  status = 301
  force = true

# Redirect old URLs if any
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404